### CREATE five documents.
POST http://localhost:3000/travels HTTP/1.1
content-type: application/json

{
    "placeName": "Japan",
    "dateWent": "2000-08-10",
    "daysSpent": "5"
}


### CREATE 2
POST http://localhost:3000/travels HTTP/1.1
content-type: application/json

{
    "placeName": "New Mexico",
    "dateWent": "2010-10-10",
    "daysSpent": "2"
}

### CREATE 3
POST http://localhost:3000/travels HTTP/1.1
content-type: application/json

{
    "placeName": "England",
    "dateWent": "2023-08-09",
    "daysSpent": "50"
}

### CREATE 4
POST http://localhost:3000/travels HTTP/1.1
content-type: application/json

{
    "placeName": "Poland",
    "dateWent": "1899-06-02",
    "daysSpent": "7"
}

### CREATE 5
POST http://localhost:3000/travels HTTP/1.1
content-type: application/json

{
    "placeName": "Italy",
    "dateWent": "2016-04-12",
    "daysSpent": "6"
}


### RETRIEVE all documents.
GET http://localhost:3000/travels HTTP/1.1



### RETRIEVE a document by its ID.
### Replace the following ID with one that exists in the collection.
GET http://localhost:3000/travels/64d53ff50688e65edbdd82bf HTTP/1.1


### UPDATE one document's year, by ID.
### Replace the ID in the following request with one that exists
### and update the year:
PUT http://localhost:3000/travels/64d53ff50688e65edbdd82bf HTTP/1.1
content-type: application/json

{
    "placeName": "India",
    "dateWent": "1940-08-10",
    "daysSpent": "13"
}

### DELETE by ID (responds with nothing if successful):
DELETE http://localhost:3000/travels/64d53ff50688e65edbdd82bf HTTP/1.1



### RETRIEVE all documents (responds with 4 or the original 5):
GET http://localhost:3000/travels HTTP/1.1

